### ISSUE TITLE
无法添加本地libc

### ISSUE THREAD

**Issue by wumingzhilian** [Ro0tk1t/LibcSearcher3#2]
root@ubuntu:/# libcsearch -l /home/hacker/Desktop/libc-2.31.so 
Traceback (most recent call last):
  File "/usr/local/bin/libcsearch", line 11, in <module>
    load_entry_point('LibcSearcher3', 'console_scripts', 'libcsearch')()
  File "/LibcSearcher3/LibcSearcher3/main.py", line 118, in main
    parse_libc(parser.local_libc)
  File "/LibcSearcher3/LibcSearcher3/utils.py", line 27, in parse_libc
    proc = subprocess.Popen(cmd)
  File "/usr/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'scripts/add': 'scripts/add'

**Comment by Ro0tk1t** [comment]
已修复

`pip install LibcSearcher3==1.3.0`
